# Generated by Django 5.0.6 on 2024-07-11 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='currency_icons/')),
                ('type', models.CharField(blank=True, choices=[('fiat', 'Фиатная валюта'), ('crypto', 'Криптовалюта'), ('eps', 'Электронная платёжная система'), ('other', 'Другое')], max_length=20, null=True)),
                ('base_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО отправителя')),
                ('sberbank_card_number', models.CharField(max_length=18, verbose_name='Карта Сбербанка')),
                ('tether_wallet', models.CharField(max_length=255, verbose_name='Кошелёк Tether (TRC20)')),
                ('agree_to_exchange_rules', models.BooleanField(verbose_name='Я согласен с правилами обмена и политикой AML')),
            ],
            options={
                'verbose_name': 'Реквизиты оплаты',
                'verbose_name_plural': 'Реквизиты оплаты',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='valut.paymentdetails')),
            ],
            options={
                'verbose_name': 'История платежей',
                'verbose_name_plural': 'История платежей',
            },
        ),
    ]
