# Generated by Django 5.0.6 on 2024-06-27 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('deposit_status_all', models.BooleanField()),
                ('receive_status_all', models.BooleanField()),
                ('default_form_value', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Криптовалюта',
                'verbose_name_plural': 'Криптовалюты',
            },
        ),
        migrations.CreateModel(
            name='FiatCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetCode', models.CharField(max_length=10)),
                ('assetName', models.CharField(max_length=255)),
                ('assetLogo', models.URLField()),
                ('size', models.IntegerField()),
                ('fiatMinLimit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fiatMaxLimit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cryptoMinLimit', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('cryptoMaxLimit', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('quotation', models.CharField(blank=True, max_length=255, null=True)),
                ('suggestAmounts', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Фиатная валюта',
                'verbose_name_plural': 'Фиатные валюты',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(help_text="Кошелёк, например, 'кошелёк мбанк мобильный кошелёк'", max_length=255)),
                ('send_currency', models.CharField(choices=[('fiat', 'Фиатная валюта'), ('crypto', 'Криптовалюта')], help_text='Тип отправляемой валюты', max_length=50)),
                ('send_amount', models.DecimalField(decimal_places=8, help_text='Отправляемая сумма', max_digits=20)),
                ('receive_currency', models.CharField(choices=[('fiat', 'Фиатная валюта'), ('crypto', 'Криптовалюта')], help_text='Тип получаемой валюты', max_length=50)),
                ('receive_amount', models.DecimalField(decimal_places=8, help_text='Получаемая сумма', max_digits=20)),
                ('fee', models.DecimalField(decimal_places=2, help_text='Комиссия за транзакцию', max_digits=10)),
                ('send_method', models.CharField(help_text="Способ отправки, например, 'банки, есть там сбербанка или киви'", max_length=255)),
                ('receive_method', models.CharField(help_text="Способ получения, например, 'денег, криптовалюта'", max_length=255)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deposit', models.BooleanField()),
                ('receive', models.BooleanField()),
                ('is_default', models.BooleanField()),
                ('confirmations_minimum', models.IntegerField()),
                ('confirmations_maximum', models.IntegerField()),
                ('withdraw_decimals_minimum', models.IntegerField()),
                ('regex_address', models.CharField(max_length=255)),
                ('regex_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('has_tag', models.BooleanField()),
                ('tag_name', models.CharField(blank=True, max_length=50, null=True)),
                ('explorer', models.URLField()),
                ('explorer_hash', models.URLField()),
                ('explorer_address', models.URLField()),
                ('confirmation_minutes_range', models.CharField(max_length=20)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='currency.coin')),
            ],
        ),
    ]
