# Generated by Django 5.0.6 on 2024-07-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_fiatcurrency_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiatcurrency',
            old_name='assetCode',
            new_name='code',
        ),
    ]
