# Generated by Django 5.0.6 on 2024-07-04 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_rename_assetcode_fiatcurrency_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название банка')),
                ('logo', models.ImageField(upload_to='bank_logos/', verbose_name='Логотип банка')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='currency.fiatcurrency')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
    ]
