# Generated by Django 5.0.6 on 2024-07-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='currency',
        ),
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.URLField(),
        ),
    ]
