# Generated by Django 5.0.6 on 2024-07-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_remove_bank_currency_alter_bank_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.RemoveField(
            model_name='fiatcurrency',
            name='assetName',
        ),
        migrations.AlterField(
            model_name='fiatcurrency',
            name='assetLogo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiatcurrency',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
