# Generated by Django 5.0.6 on 2024-07-02 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('fio_sender', models.CharField(max_length=100, verbose_name='ФИО отправителя')),
                ('sberbank_card', models.CharField(max_length=18, verbose_name='Карта Сбербанка')),
                ('tether_wallet', models.CharField(max_length=100, verbose_name='Кошелек Tether (TRC20)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('approved', 'Одобрен'), ('failed', 'Неуспешный'), ('completed', 'Завершен')], default='created', max_length=20, verbose_name='Статус платежа')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, verbose_name='ID транзакции')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('approved', 'Одобрен'), ('failed', 'Неуспешный'), ('completed', 'Завершен')], default='created', max_length=20, verbose_name='Статус транзакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.payment', verbose_name='Платеж')),
            ],
        ),
    ]
