# Generated by Django 5.0.6 on 2024-07-15 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.URLField()),
                ('buy', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sell', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('source_decimal', models.IntegerField(default=1)),
                ('target_decimal', models.IntegerField(default=1)),
                ('source_regex', models.CharField(max_length=100)),
                ('target_regex', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Фиат', 'Фиат'), ('Криптовалюта', 'Криптовалюта')], max_length=50)),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_currency_pairs', to='valuts.currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_currency_pairs', to='valuts.currency')),
            ],
        ),
    ]
