# Generated by Django 5.0.6 on 2024-06-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapps', '0002_application_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
