# Generated by Django 5.0.6 on 2024-06-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Русский язык')], default='en', max_length=255, null=True, verbose_name='Язык')),
                ('number', models.CharField(max_length=100, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('direction', models.CharField(max_length=100, verbose_name='Направление')),
                ('direct', models.CharField(max_length=100, verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='От')),
                ('end_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='До')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Русский язык')], default='en', max_length=255, null=True, verbose_name='Язык')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
                ('participation_instructions', models.TextField(verbose_name='Инструкции по участию')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Реферальная программа',
                'verbose_name_plural': 'Реферальная программа',
            },
        ),
    ]
