# Generated by Django 5.0.6 on 2024-06-24 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Русский язык')], default='en', max_length=255, null=True, verbose_name='Язык')),
                ('number', models.CharField(max_length=100, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('direction', models.CharField(max_length=100, verbose_name='Направление')),
                ('direct', models.CharField(max_length=100, verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Веб-сайт')),
                ('sender', models.EmailField(max_length=254, verbose_name='Отправитель')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Временная метка')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Русский язык')], default='en', max_length=255, null=True, verbose_name='Язык')),
                ('participants', models.IntegerField(default=15, verbose_name='Количество участников')),
                ('prize_amount', models.DecimalField(decimal_places=2, default=1300, max_digits=10, verbose_name='Банк конкурса')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок завершения')),
                ('participation_instructions', models.TextField(default='\n1. Совершить обмен на нашем сервисе onemoment.cc\n2. Подписаться на телеграмм канал @onemomentinfo\n3. Написать отзыв на bestchange.ru в день совершения обмена\n4. Убедиться в том, что номер обмена и email в отзыве совпадают с email, который указывался в заявке на обмен\n5. Проверить результаты розыгрыша в пятницу 18:00 в нашем телеграм канале @onemomentinfo', verbose_name='Инструкции по участию')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Конкурс',
                'verbose_name_plural': 'Конкурсы',
            },
        ),
        migrations.CreateModel(
            name='CurrencyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Русский язык')], default='en', max_length=255, null=True, verbose_name='Язык')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='От')),
                ('end_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='До')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Русский язык')], default='en', max_length=255, null=True, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Правило обмена',
                'verbose_name_plural': 'Правила обмена',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Русский язык')], default='en', max_length=255, null=True, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='footer_images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Веб-сайт',
                'verbose_name_plural': 'Веб-сайт',
            },
        ),
        migrations.CreateModel(
            name='KYCAMLCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Русский язык')], default='en', max_length=255, null=True, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'KYC/AML Запись',
                'verbose_name_plural': 'KYC/AML Записи',
            },
        ),
        migrations.CreateModel(
            name='OneMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Русский язык')], default='en', max_length=255, null=True, verbose_name='Язык')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Один момент',
                'verbose_name_plural': 'Одни моменты',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор отзыва')),
                ('content', models.TextField(verbose_name='Текст отзыва')),
                ('date_posted', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
