# Generated by Django 5.0.6 on 2024-06-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getapps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
